# Site settings
title: Nic West
email: nicwest.cb@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal blog of nic west, likely just ramblings about vim.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nic-west.com" # the base hostname & protocol for your site
twitter_username: west_nic
github_username:  nicwest
exclude:
  - divshot.json

# Build settings
markdown: kramdown
permalink: "/:title/"
